version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_build:
      commands:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    
    build:
      commands:
        - python manage.py collectstatic --noinput
        - python manage.py migrate --noinput

python:
  version: 3.11
  install:
    - requirements: requirements.txt
